"""add Chain and Contract model

Revision ID: 6821ca065b2e
Revises: 823286edf8f5
Create Date: 2021-02-28 18:33:11.445025

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6821ca065b2e"
down_revision = "823286edf8f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chains",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "contracts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("chain", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chain"],
            ["chains.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contracts")
    op.drop_table("chains")
    # ### end Alembic commands ###
