"""Add ContractOracle model

Revision ID: 8bf91192e068
Revises:
Create Date: 2020-12-30 13:58:11.924401

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8bf91192e068"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contract_oracles",
        sa.Column("id", sa.String(length=42), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contract_oracles")
    # ### end Alembic commands ###
