"""add chains table

Revision ID: bc8b9852d38e
Revises: 8bf91192e068
Create Date: 2021-02-06 17:11:22.242596

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bc8b9852d38e"
down_revision = "8bf91192e068"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chains",
        sa.Column("name", sa.String(length=42), nullable=False),
        sa.Column("chain_type", sa.String(length=42), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.add_column(
        "contract_oracles", sa.Column("chain", sa.String(length=42), nullable=True)
    )
    op.create_foreign_key(
        "contract_oracles_chain_fkey", "contract_oracles", "chains", ["chain"], ["name"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "contract_oracles_chain_fkey", "contract_oracles", type_="foreignkey"
    )
    op.drop_column("contract_oracles", "chain")
    op.drop_table("chains")
    # ### end Alembic commands ###
